### ISSUE TITLE
After register/login not showing anything

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-mobile#1]
After login and register not anything happen.

**Comment by isnancahyadi** [comment]
Sorry, I'm not understand about that error. Can you tell me the details, please ? Thank You.

**Comment by isnancahyadi** [comment]
I have fixed it. Thank You.
![1691661555533](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/97781402/483efc82-ab47-4b4d-a514-90e43fd16b05)
![1691661555537](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/97781402/effad275-804d-4484-b9a6-2f6becfcda2d)
