### ISSUE TITLE
Change your icon app and title app

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-mobile#2]
![photo1691638505](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/49361887/6c637fc0-3f8c-406b-9078-9a61f5ca5203)

**Comment by isnancahyadi** [comment]
I have fixed it. Thank You.
![1691662475197](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/97781402/68cc000c-232d-41c2-b770-a7a9b20dcb49)
