### ISSUE TITLE
Add recipe layout not done

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-mobile#3]
![photo_6255985952912684735_y](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/49361887/a7192379-3c16-4e8f-9425-78b33e16053a)

**Comment by isnancahyadi** [comment]
I have fixed it. Thank you.
![1691987158403](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/97781402/751bdc4d-6186-4e79-9a17-fb280806a705)
