### ISSUE TITLE
Feature search not found

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-mobile#4]
![photo_6255985952912684736_y](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/49361887/a1de4313-fbc8-487e-bb7c-705e22079255)

**Comment by isnancahyadi** [comment]
I have fixed it. Thank you.
![1692023839151](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/97781402/1bd14278-5ee5-4d5d-ab8a-8271a5e76490)
