### ISSUE TITLE
Recipe in found blank and category not working

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-mobile#5]
![photo_6253665571061217383_y](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/49361887/0a011f83-2e7c-4c5f-9ecc-92c6aa81e94f)

**Comment by isnancahyadi** [comment]
I have fixed it and category was working. Thank you.
![1691987158394](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/97781402/d44d519f-acce-4016-8546-064d1b3141ad)
![1691987158409](https://github.com/isnancahyadi/pijar-cooking-mobile/assets/97781402/ba2c6777-2f8c-4dc4-8c40-70bc7a86c60a)
